-- Natural slow-traffic pileup for Scenario Engine v2, Commit 7.1.
-- Final lead and follower braking are transient pulses. Car A returns to a
-- FOLLOWING state behind moving Car F instead of stopping on an open road.
return {
  id = 'sudden_obstacle_pileup',
  version = 10,
  name = 'natural_slow_traffic_pileup_v2_1',
  phase = 'scenario_engine_v2_commit7_1_transient_braking',
  description = 'Progressive lead deceleration, transient braking pulses, following a moving slow vehicle, delayed close follower response, and ambient traffic.',

  preferredStraightLengths = {420, 380, 340, 300},
  minimumDrivability = 0.25,
  lanePreference = 'outer',
  driveInLane = true,

  ambientTraffic = {
    enabled = true,
    count = 6,
    excludeScenarioLane = true,
    fallbackToScenarioLane = false,
    driveInLane = true,
    aggression = 0.35,
    speedRange = {12.5, 16.5},
    models = {'midsize', 'etk800', 'covet'},
    fallbackModels = {'etk800', 'covet', 'midsize'},
    edgeMargin = 22,
    longitudinalJitter = 8,
    lateralJitter = 0.12,
    minimumSpacing = 28,
    oppositeFlow = {
      enabled = true,
      count = 3,
      minimumLateralSeparation = 5,
      maximumLateralSeparation = 45,
      maximumLongitudinalOffset = 180,
      maximumVerticalDifference = 8,
      parallelDotThreshold = 0.82,
      minimumEdgeLength = 6,
      minimumStraightLength = 180,
      spawnHalfSpan = 150,
      continuationDotThreshold = 0.72,
      maintainOppositeDotThreshold = 0.60,
      corridorDotThreshold = 0.82,
      maximumCorridorCandidates = 24,
      maximumCorridorNodesPerSide = 18,
      maximumTargetPathNodes = 14,
      targetPathDistance = 700,
    },
  },

  scenarioDuration = 30.0,
  maximumScenarioTime = 42.0,
  desiredNormalDriveTime = 12.0,
  initialSpacingTriggerId = 'lead_coasts_to_hazard',

  -- Compatibility/debug values. The final reactions use TTC first and distance
  -- only when TTC is genuinely unavailable.
  leadBrakeDistance = 9.0,
  targetBrakeDistance = 7.0,
  targetBrakeAmount = 0.22,

  reactionModel = {
    leadCoastTtcSeconds = 5.00,
    leadDecelerateTtcSeconds = 3.20,
    leadEmergencyTtcSeconds = 1.65,
    targetTtcSeconds = 1.45,
    targetReactionDelaySeconds = 0.75,
    targetEmergencyTtcSeconds = 0.62,
    targetEmergencyDelaySeconds = 0.08,
    minimumClosingSpeedMps = 0.35,
  },

  bindings = {
    lead = 'Car A',
    target = 'Car B',
    hazard = 'Car F',
  },

  convoy = {
    {label = 'Car A', role = 'lead_driver', model = 'etk800', gapBehind = 0,  lateralOffset = 0.00, speedMps = 14.0},
    {label = 'Car B', role = 'late_reacting_follower', model = 'covet', gapBehind = 24, lateralOffset = 0.08, speedMps = 14.3},
    {label = 'Car C', role = 'primary_striker', model = 'etk800', gapBehind = 28, lateralOffset = -0.20, speedMps = 15.2},
    {label = 'Car D', role = 'secondary_striker', model = 'covet', gapBehind = 32, lateralOffset = 0.26, speedMps = 15.7},
    {label = 'Car E', role = 'background_traffic', model = 'etk800', gapBehind = 32, lateralOffset = -0.14, speedMps = 14.9},
  },

  -- The hazard is visibly ahead of Car A in the same lane and keeps moving.
  hazard = {
    label = 'Car F',
    role = 'slow_hazard',
    model = 'covet',
    lateralOffset = 0.04,
    speedMps = 6.5,
  },

  triggers = {
    -- Stage 1: the lead driver notices slower traffic and eases off early.
    {
      id = 'lead_coasts_to_hazard',
      group = 'lead_coast',
      subject = 'Car A',
      target = 'Car F',
      metric = 'ttc',
      operator = '<=',
      threshold = 5.00,
      minRelativeSpeed = 0.35,
      once = true,
      requirePositiveDistance = true,
      phase = 'lead_coasting',
      action = {
        type = 'set_speed',
        actor = 'Car A',
        speedMps = 11.2,
        controllerState = 'COASTING',
      },
    },

    -- Stage 2: a visible, stronger but still controlled speed reduction.
    {
      id = 'lead_decelerates_to_hazard',
      group = 'lead_decelerate',
      requiresGroup = 'lead_coast',
      subject = 'Car A',
      target = 'Car F',
      metric = 'ttc',
      operator = '<=',
      threshold = 3.20,
      minRelativeSpeed = 0.35,
      once = true,
      requirePositiveDistance = true,
      phase = 'lead_decelerating',
      action = {
        type = 'set_speed',
        actor = 'Car A',
        speedMps = 8.4,
        controllerState = 'DECELERATING',
      },
    },

    -- Stage 3: final braking, after the two visible deceleration stages.
    {
      id = 'lead_reacts_to_hazard',
      group = 'lead_brake',
      requiresGroup = 'lead_decelerate',
      subject = 'Car A',
      target = 'Car F',
      metric = 'ttc',
      operator = '<=',
      threshold = 1.65,
      minRelativeSpeed = 0.35,
      once = true,
      requirePositiveDistance = true,
      phase = 'hazard_reaction',
      legacyFlag = 'leadBrakeTriggered',
      legacyTimestamp = 'brakeTriggeredAt',
      action = {
        type = 'brake_pulse',
        actor = 'Car A',
        amount = 0.58,
        duration = 0.85,
        mode = 'controlled',
        releaseState = 'FOLLOWING',
        releaseSpeedMps = 6.7,
        followTarget = 'Car F',
        speedOffsetMps = 0.2,
        commandName = 'leadProgressiveFinalBrakePulse',
      },
    },

    {
      id = 'lead_distance_fallback',
      group = 'lead_brake',
      requiresGroup = 'lead_decelerate',
      subject = 'Car A',
      target = 'Car F',
      metric = 'distance',
      operator = '<=',
      threshold = 9.0,
      fallbackFor = 'lead_reacts_to_hazard',
      fallbackUnavailableSeconds = 0.40,
      once = true,
      requirePositiveDistance = true,
      phase = 'hazard_reaction',
      legacyFlag = 'leadBrakeTriggered',
      legacyTimestamp = 'brakeTriggeredAt',
      action = {
        type = 'brake_pulse',
        actor = 'Car A',
        amount = 0.72,
        duration = 0.95,
        mode = 'controlled',
        releaseState = 'FOLLOWING',
        releaseSpeedMps = 6.7,
        followTarget = 'Car F',
        speedOffsetMps = 0.2,
        commandName = 'leadProgressiveDistanceFallbackPulse',
      },
    },

    -- Car B reacts later and initially applies only light braking. This avoids
    -- the previous large, artificial stopping gap behind Car A.
    {
      id = 'target_reacts_to_lead',
      group = 'target_brake',
      requiresGroup = 'lead_decelerate',
      subject = 'Car B',
      target = 'Car A',
      metric = 'ttc',
      operator = '<=',
      threshold = 1.45,
      minRelativeSpeed = 0.35,
      delaySeconds = 0.75,
      once = true,
      requirePositiveDistance = true,
      phase = 'collision_window',
      legacyFlag = 'targetBrakeTriggered',
      legacyTimestamp = 'targetBrakeTriggeredAt',
      action = {
        type = 'brake_pulse',
        actor = 'Car B',
        amount = 0.22,
        duration = 0.68,
        releaseState = 'CRUISE',
        releaseSpeedMps = 14.0,
        commandName = 'targetLateLightBrakePulse',
      },
    },

    {
      id = 'target_distance_fallback',
      group = 'target_brake',
      requiresGroup = 'lead_decelerate',
      subject = 'Car B',
      target = 'Car A',
      metric = 'distance',
      operator = '<=',
      threshold = 7.0,
      fallbackFor = 'target_reacts_to_lead',
      fallbackUnavailableSeconds = 0.35,
      delaySeconds = 0.75,
      once = true,
      requirePositiveDistance = true,
      phase = 'collision_window',
      legacyFlag = 'targetBrakeTriggered',
      legacyTimestamp = 'targetBrakeTriggeredAt',
      action = {
        type = 'brake_pulse',
        actor = 'Car B',
        amount = 0.22,
        duration = 0.68,
        releaseState = 'CRUISE',
        releaseSpeedMps = 14.0,
        commandName = 'targetLateLightDistanceFallbackPulse',
      },
    },

    -- A separate final stage only appears when Car B is genuinely about to hit.
    {
      id = 'target_emergency_to_lead',
      group = 'target_emergency',
      requiresGroup = 'target_brake',
      subject = 'Car B',
      target = 'Car A',
      metric = 'ttc',
      operator = '<=',
      threshold = 0.62,
      minRelativeSpeed = 0.35,
      delaySeconds = 0.08,
      once = true,
      requirePositiveDistance = true,
      phase = 'target_emergency',
      action = {
        type = 'brake',
        actor = 'Car B',
        amount = 0.82,
        mode = 'emergency',
        commandName = 'targetCloseEmergencyBrake',
      },
    },

    {
      id = 'target_emergency_distance_fallback',
      group = 'target_emergency',
      requiresGroup = 'target_brake',
      subject = 'Car B',
      target = 'Car A',
      metric = 'distance',
      operator = '<=',
      threshold = 2.0,
      fallbackFor = 'target_emergency_to_lead',
      fallbackUnavailableSeconds = 0.15,
      once = true,
      requirePositiveDistance = true,
      phase = 'target_emergency',
      action = {
        type = 'brake',
        actor = 'Car B',
        amount = 0.88,
        mode = 'emergency',
        commandName = 'targetCloseEmergencyDistanceFallback',
      },
    },
  },
}
